/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Astral: typeof import('./src/components/Background/Astral.vue')['default']
    Background: typeof import('./src/components/Background/index.vue')['default']
    Bubbling: typeof import('./src/components/Background/Bubbling.vue')['default']
    ComponentMode: typeof import('./src/components/Draggable/ComponentMode.vue')['default']
    Dialog: typeof import('./src/components/Dialog/index.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElText: typeof import('element-plus/es')['ElText']
    FunctionMode: typeof import('./src/components/Draggable/FunctionMode.vue')['default']
    Header: typeof import('./src/components/Header/index.vue')['default']
    InstructionMode: typeof import('./src/components/Draggable/InstructionMode.vue')['default']
    Rainbow: typeof import('./src/components/Rainbow/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Setting: typeof import('./src/components/Header/Setting.vue')['default']
    Signature: typeof import('./src/components/Header/Signature.vue')['default']
    Skill: typeof import('./src/components/Skill/index.vue')['default']
    Starport: typeof import('vue-starport')['Starport']
    StarportCarrier: typeof import('vue-starport')['StarportCarrier']
    StreetLamp: typeof import('./src/components/Background/StreetLamp.vue')['default']
    Test1: typeof import('./src/components/Dialog/Test1.vue')['default']
    Test2: typeof import('./src/components/Dialog/Test2.vue')['default']
    Theme: typeof import('./src/components/Header/Theme.vue')['default']
  }
}
